### ISSUE TITLE
Unity URP 2022.3.36f1 Compile Error on import

### ISSUE THREAD

**Issue by jamesarndt82** [Pjbomb2/Compute-Shader-Unity-PathTracer#23]
Assets\TrueTrace\Resources\Utility\Atmosphere\AtmosphereGenerator.cs(4,7): error CS0246: The type or namespace name 'CommonVars' could not be found (are you missing a using directive or an assembly reference?)

**Comment by Pjbomb2** [comment]
Sorry, I uploaded the wrong file, fixing it now
